version: '3.1'

services:
  postgres:
    image: postgres:15-alpine3.18
    environment:
      - POSTGRES_USER=film
      - POSTGRES_PASSWORD=film445566
      - POSTGRES_DB=filmfans
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - /data-postgresql:/var/lib/postgresql/data
    ports:
      - '5432:5432'
